### ISSUE TITLE
Provider: Openstack (EC2-compatible metadata API)

### ISSUE THREAD

**Issue by jvrplmlmn** [clstokes/aero#5]
Hi @clstokes,

I wonder how we could make a distinction between `OpenStack` and `Amazon` taking into account that `OpenStack` has a [EC2-compatible metadata API](http://docs.openstack.org/admin-guide/compute-networking-nova.html#metadata-service).

Alternatively we could use the native OpenStack metadata, but in this case some JSON tinkering will be necessary.

**Comment by clstokes** [comment]
I'd prefer to use the native OpenStack metadata service. JSON tinkering is fine. I plan to document that aero will "normalize" data to some extent.

@jvrplmlmn, if you have access to an OpenStack instance, a metadata dump (ie. `wget --recursive ...`) would be a great help!

**Comment by jvrplmlmn** [comment]
@clstokes I'll try to implement it myself, need to practice my golang 😆  

Taking into account that an OpenStack instance can reply to both the native and the EC2 compatible metadata APIs, I see a small issue with the current implementation of the [`getCurrentProvider`](https://github.com/clstokes/aero/blob/36bf8d57871d66e0dceaed4ab6ea90bca2cbe5b4/main.go#L50-L58). This method iterates over a map ([`fingerprinters`](https://github.com/clstokes/aero/blob/36bf8d57871d66e0dceaed4ab6ea90bca2cbe5b4/main.go#L16-L19)) which in Golang if I'm not mistaken are randomized. So it could be possible that we determine that the provider is Amazon instead of OpenStack.

Ninja edit, can be seen here:

```
 aero git:(master) ✗ ./bin/aero
google
amazon
Unknown provider.
 aero git:(master) ✗ ./bin/aero
google
amazon
Unknown provider.
 aero git:(master) ✗ ./bin/aero
amazon
google
Unknown provider.
 aero git:(master) ✗ ./bin/aero
amazon
google
Unknown provider.
 aero git:(master) ✗ ./bin/aero
amazon
google
Unknown provider.
 aero git:(master) ✗ ./bin/aero
amazon
google
Unknown provider.
 aero git:(master) ✗
```

Any ideas on how we can solve this?

**Comment by clstokes** [comment]
Yea, the current fingerprint technique is pretty naive, but I'm sure there's some metadata value we can use to deterministically identify AWS vs AWS-compatible OpenStack. I'll do some research.

**Comment by jvrplmlmn** [comment]
This is the information that we can retrieve from the OpenStack native meta-data API:

```
ubuntu@ubuntu-xenial-1:~$ curl --silent http://169.254.169.254/openstack/latest/meta_data.json | python -m json.tool
{
    "availability_zone": "node1",
    "hostname": "ubuntu-xenial-1.novalocal",
    "keys": [
        {
            "data": "ssh-rsa AAAAB3NzaC1yc2E...... root@localhost",
            "name": "root",
            "type": "ssh"
        }
    ],
    "launch_index": 0,
    "name": "ubuntu-xenial-1",
    "project_id": "b16238b59fed4f3db48e87eaf17fc5a3",
    "public_keys": {
        "user": "ssh-rsa AAAAB3NzaC1yc2E...... root@localhost"
    },
    "random_seed": "0yT/nrwFMcEk7q8uBxjxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "uuid": "e51aa9ba-e9b4-43fe-8cc7-7939ad5ed5cb"
}
ubuntu@ubuntu-xenial-1:~$ 

```

```
ubuntu@ubuntu-xenial-1:~$ curl --silent http://169.254.169.254/openstack/latest/network_data.json | python -m json.tool
{
    "links": [
        {
            "ethernet_mac_address": "fa:16:3e:0a:6d:9e",
            "id": "tap01241d2e-2b",
            "mtu": null,
            "type": "ovs",
            "vif_id": "01241d2e-2b17-4b3e-8bb5-6f4c6da37e95"
        },
        {
            "ethernet_mac_address": "fa:16:3e:18:1c:fa",
            "id": "tapfe870571-0e",
            "mtu": null,
            "type": "ovs",
            "vif_id": "fe870571-0ee7-4934-83df-c4d7c5c10c24"
        }
    ],
    "networks": [
        {
            "id": "network0",
            "link": "tap01241d2e-2b",
            "network_id": "9048c168-1c46-4850-846e-d99e0168afc6",
            "type": "ipv4_dhcp"
        },
        {
            "id": "network1",
            "link": "tapfe870571-0e",
            "network_id": "6c3bde69-3a4a-45e5-9eaa-2fa341f9c960",
            "type": "ipv4_dhcp"
        }
    ],
    "services": [
        {
            "address": "xx.yy.zz.ww",
            "type": "dns"
        },
        {
            "address": "xx.yy.zz.wa",
            "type": "dns"
        }
    ]
}
ubuntu@ubuntu-xenial-1:~$ 

```

```
ubuntu@ubuntu-xenial-1:~$ curl --silent http://169.254.169.254/openstack/latest/vendor_data.json | python -m json.tool
{}
ubuntu@ubuntu-xenial-1:~$
```

As you can, we cannot retrieve 2 of the default metadata keys of `aero`: `address-private` and `address-public`.

I did some additional digging and the EC2-compatible metadata API comes enabled by default in OpenStack, so for me it makes more sense to try and follow that route.

**Comment by clstokes** [comment]
Is `xx.yy.zz.ww` what's actually returned by the service or did you mask those?

Can you provide a dump of the EC2-compatible API too? The `.json` ones from the OpenStack service are very helpful.

**Comment by jvrplmlmn** [comment]
I masked those values, they were the IP addresses of the DNS servers in the OpenStack deployment.

Sadly I don't have access to an OpenStack deployment for the time being, but the EC2-compatible API is the same thing as if you were querying an actual EC2 instance:

```
$ curl http://169.254.169.254/latest/meta-data/
reservation-id
public-keys/
security-groups
public-ipv4
ami-manifest-path
instance-type
instance-id
local-ipv4
local-hostname
placement/
ami-launch-index
public-hostname
hostname
ami-id
instance-action
```
